insert into public.languages (name, slug)
values
  ('Afar', 'afar'),
  ('Abkhazian', 'abkhazian'),
  ('Avestan', 'avestan'),
  ('Afrikaans', 'afrikaans'),
  ('Akan', 'akan'),
  ('Amharic', 'amharic'),
  ('Aragonese', 'aragonese'),
  ('Arabic', 'arabic'),
  ('Assamese', 'assamese'),
  ('Avaric', 'avaric'),
  ('Aymara', 'aymara'),
  ('Azerbaijani', 'azerbaijani'),
  ('Bashkir', 'bashkir'),
  ('Belarusian', 'belarusian'),
  ('Bulgarian', 'bulgarian'),
  ('Bislama', 'bislama'),
  ('Bambara', 'bambara'),
  ('Bengali', 'bengali'),
  ('Tibetan', 'tibetan'),
  ('Breton', 'breton'),
  ('Bosnian', 'bosnian'),
  ('Catalan', 'catalan'),
  ('Cantonese', 'cantonese'),
  ('Chechen', 'chechen'),
  ('Chamorro', 'chamorro'),
  ('Corsican', 'corsican'),
  ('Cree', 'cree'),
  ('Czech', 'czech'),
  ('Church Slavic', 'church-slavic'),
  ('Chuvash', 'chuvash'),
  ('Welsh', 'welsh'),
  ('Danish', 'danish'),
  ('German', 'german'),
  ('Divehi', 'divehi'),
  ('Dzongkha', 'dzongkha'),
  ('Ewe', 'ewe'),
  ('Greek', 'greek'),
  ('English', 'english'),
  ('Esperanto', 'esperanto'),
  ('Spanish', 'spanish'),
  ('Estonian', 'estonian'),
  ('Basque', 'basque'),
  ('Persian', 'persian'),
  ('Fulah', 'fulah'),
  ('Finnish', 'finnish'),
  ('Fijian', 'fijian'),
  ('Faroese', 'faroese'),
  ('French', 'french'),
  ('Western Frisian', 'western-frisian'),
  ('Irish', 'irish'),
  ('Scottish Gaelic', 'scottish-gaelic'),
  ('Galician', 'galician'),
  ('Guarani', 'guarani'),
  ('Gujarati', 'gujarati'),
  ('Manx', 'manx'),
  ('Hausa', 'hausa'),
  ('Hebrew', 'hebrew'),
  ('Hindi', 'hindi'),
  ('Hiri Motu', 'hiri-motu'),
  ('Croatian', 'croatian'),
  ('Haitian Creole', 'haitian-creole'),
  ('Hungarian', 'hungarian'),
  ('Armenian', 'armenian'),
  ('Herero', 'herero'),
  ('Interlingua', 'interlingua'),
  ('Indonesian', 'indonesian'),
  ('Interlingue', 'interlingue'),
  ('Igbo', 'igbo'),
  ('Sichuan Yi', 'sichuan-yi'),
  ('Inupiaq', 'inupiaq'),
  ('Ido', 'ido'),
  ('Icelandic', 'icelandic'),
  ('Italian', 'italian'),
  ('Inuktitut', 'inuktitut'),
  ('Japanese', 'japanese'),
  ('Javanese', 'javanese'),
  ('Georgian', 'georgian'),
  ('Kongo', 'kongo'),
  ('Kikuyu', 'kikuyu'),
  ('Kwanyama', 'kwanyama'),
  ('Kazakh', 'kazakh'),
  ('Kalaallisut', 'kalaallisut'),
  ('Central Khmer', 'central-khmer'),
  ('Kannada', 'kannada'),
  ('Korean', 'korean'),
  ('Kanuri', 'kanuri'),
  ('Kashmiri', 'kashmiri'),
  ('Kurdish', 'kurdish'),
  ('Komi', 'komi'),
  ('Cornish', 'cornish'),
  ('Kirghiz', 'kirghiz'),
  ('Latin', 'latin'),
  ('Luxembourgish', 'luxembourgish'),
  ('Ganda', 'ganda'),
  ('Limburgan', 'limburgan'),
  ('Lingala', 'lingala'),
  ('Lao', 'lao'),
  ('Lithuanian', 'lithuanian'),
  ('Luba-Katanga', 'luba-katanga'),
  ('Latvian', 'latvian'),
  ('Malagasy', 'malagasy'),
  ('Mandarin', 'mandarin'),
  ('Marshallese', 'marshallese'),
  ('Maori', 'maori'),
  ('Macedonian', 'macedonian'),
  ('Malayalam', 'malayalam'),
  ('Mongolian', 'mongolian'),
  ('Marathi', 'marathi'),
  ('Malay', 'malay'),
  ('Maltese', 'maltese'),
  ('Burmese', 'burmese'),
  ('Nauru', 'nauru'),
  ('Norwegian Bokmal', 'norwegian-bokmal'),
  ('North Ndebele', 'north-ndebele'),
  ('Nepali', 'nepali'),
  ('Ndonga', 'ndonga'),
  ('Dutch', 'dutch'),
  ('Norwegian Nynorsk', 'norwegian-nynorsk'),
  ('Norwegian', 'norwegian'),
  ('South Ndebele', 'south-ndebele'),
  ('Navajo', 'navajo'),
  ('Chichewa', 'chichewa'),
  ('Occitan', 'occitan'),
  ('Ojibwa', 'ojibwa'),
  ('Oromo', 'oromo'),
  ('Odia', 'odia'),
  ('Ossetian', 'ossetian'),
  ('Punjabi', 'punjabi'),
  ('Pali', 'pali'),
  ('Polish', 'polish'),
  ('Pashto', 'pashto'),
  ('Portuguese', 'portuguese'),
  ('Quechua', 'quechua'),
  ('Romansh', 'romansh'),
  ('Rundi', 'rundi'),
  ('Romanian', 'romanian'),
  ('Russian', 'russian'),
  ('Kinyarwanda', 'kinyarwanda'),
  ('Sanskrit', 'sanskrit'),
  ('Sardinian', 'sardinian'),
  ('Sindhi', 'sindhi'),
  ('Northern Sami', 'northern-sami'),
  ('Sango', 'sango'),
  ('Sinhala', 'sinhala'),
  ('Slovak', 'slovak'),
  ('Slovenian', 'slovenian'),
  ('Samoan', 'samoan'),
  ('Shona', 'shona'),
  ('Somali', 'somali'),
  ('Albanian', 'albanian'),
  ('Serbian', 'serbian'),
  ('Swati', 'swati'),
  ('Southern Sotho', 'southern-sotho'),
  ('Sundanese', 'sundanese'),
  ('Swedish', 'swedish'),
  ('Swahili', 'swahili'),
  ('Tamil', 'tamil'),
  ('Telugu', 'telugu'),
  ('Tajik', 'tajik'),
  ('Thai', 'thai'),
  ('Tigrinya', 'tigrinya'),
  ('Turkmen', 'turkmen'),
  ('Tagalog', 'tagalog'),
  ('Tswana', 'tswana'),
  ('Tonga', 'tonga'),
  ('Turkish', 'turkish'),
  ('Tsonga', 'tsonga'),
  ('Tatar', 'tatar'),
  ('Twi', 'twi'),
  ('Tahitian', 'tahitian'),
  ('Uighur', 'uighur'),
  ('Ukrainian', 'ukrainian'),
  ('Urdu', 'urdu'),
  ('Uzbek', 'uzbek'),
  ('Venda', 'venda'),
  ('Vietnamese', 'vietnamese'),
  ('Volapuk', 'volapuk'),
  ('Walloon', 'walloon'),
  ('Wolof', 'wolof'),
  ('Xhosa', 'xhosa'),
  ('Yiddish', 'yiddish'),
  ('Yoruba', 'yoruba'),
  ('Zhuang', 'zhuang'),
  ('Chinese', 'chinese'),
  ('Zulu', 'zulu')
on conflict (slug) do update
set name = excluded.name;

insert into public.categories (name, slug, description)
values
  ('Real Estate Agent', 'real-estate-agent', 'Residential, commercial, and investment real estate representation.'),
  ('Mortgage Broker', 'mortgage-broker', 'Mortgage advice, rate comparison, and financing support.'),
  ('Mortgage Agent', 'mortgage-agent', 'Mortgage applications, approvals, and borrower support.'),
  ('Home Inspector', 'home-inspector', 'Property inspection services for buyers, sellers, and owners.'),
  ('Real Estate Lawyer', 'real-estate-lawyer', 'Legal support for purchases, sales, leases, and financing.'),
  ('Notary', 'notary', 'Notary and document witnessing services for real estate transactions.'),
  ('Appraiser', 'appraiser', 'Real estate valuation and appraisal services.'),
  ('Insurance Broker', 'insurance-broker', 'Home, property, title, and real estate insurance advice.'),
  ('Contractor', 'contractor', 'Renovation, repair, and construction services.'),
  ('Electrician', 'electrician', 'Electrical repair, upgrades, inspections, and installation.'),
  ('Plumber', 'plumber', 'Plumbing repair, upgrades, fixtures, and water systems.'),
  ('HVAC Technician', 'hvac-technician', 'Heating, cooling, ventilation, and indoor air services.'),
  ('Roofer', 'roofer', 'Roof inspection, repair, replacement, and exterior protection.'),
  ('Landscaper', 'landscaper', 'Outdoor property care, landscaping, and curb appeal services.'),
  ('Pest Control Specialist', 'pest-control-specialist', 'Inspection, prevention, and treatment for pest issues.'),
  ('Real Estate Photographer', 'real-estate-photographer', 'Listing photography, video, and media services.'),
  ('Home Stager', 'home-stager', 'Home staging and presentation services for listings.'),
  ('Interior Designer', 'interior-designer', 'Interior planning, finishes, furnishings, and design consultation.'),
  ('Architect', 'architect', 'Architectural design, drawings, and renovation planning.'),
  ('Surveyor', 'surveyor', 'Land surveys, boundaries, grading, and property measurements.'),
  ('Property Manager', 'property-manager', 'Rental, tenant, and property operations management.'),
  ('Condo Document Reviewer', 'condo-document-reviewer', 'Status certificate and condo document review support.'),
  ('Property Tax Consultant', 'property-tax-consultant', 'Property assessment and tax review support.'),
  ('Mover', 'mover', 'Moving and relocation services.'),
  ('Cleaner', 'cleaner', 'Residential and move-in or move-out cleaning services.'),
  ('Junk Removal Provider', 'junk-removal-provider', 'Decluttering, disposal, and cleanout services for properties.'),
  ('Security System Installer', 'security-system-installer', 'Alarm, camera, smart lock, and home security installation.')
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description;

insert into public.specialties (category_id, name, slug, description)
select
  categories.id,
  seed_specialties.name,
  seed_specialties.slug,
  seed_specialties.description
from (
  values
    ('real-estate-agent', 'First-time buyers', 'first-time-buyers', 'Guidance for buyers purchasing their first home.'),
    ('real-estate-agent', 'Condo sales', 'condo-sales', 'Buying and selling condominium units.'),
    ('real-estate-agent', 'Luxury homes', 'luxury-homes', 'High-end residential real estate services.'),
    ('real-estate-agent', 'Investment properties', 'investment-properties', 'Support for rental and income property transactions.'),
    ('real-estate-agent', 'Commercial real estate', 'commercial-real-estate', 'Commercial purchase, sale, and lease support.'),
    ('real-estate-agent', 'Relocation clients', 'relocation-clients', 'Support for clients moving into or out of a market.'),
    ('mortgage-broker', 'First-time buyer mortgages', 'first-time-buyer-mortgages', 'Mortgage guidance for first-time home buyers.'),
    ('mortgage-broker', 'Refinancing', 'refinancing', 'Mortgage refinancing and renewal support.'),
    ('mortgage-broker', 'Self-employed mortgages', 'self-employed-mortgages', 'Financing support for self-employed borrowers.'),
    ('mortgage-broker', 'Investment property financing', 'investment-property-financing', 'Financing for rental and investment properties.'),
    ('mortgage-broker', 'Private lending', 'private-lending', 'Alternative and private mortgage options.'),
    ('mortgage-agent', 'Pre-approvals', 'pre-approvals', 'Mortgage pre-approval support and documentation review.'),
    ('mortgage-agent', 'Newcomer mortgages', 'newcomer-mortgages', 'Mortgage support for newcomers and recent immigrants.'),
    ('mortgage-agent', 'Debt consolidation', 'debt-consolidation', 'Mortgage-based debt consolidation support.'),
    ('home-inspector', 'Pre-purchase inspection', 'pre-purchase-inspection', 'Inspection before a property purchase closes.'),
    ('home-inspector', 'Pre-listing inspection', 'pre-listing-inspection', 'Inspection before a property is listed for sale.'),
    ('home-inspector', 'New construction inspection', 'new-construction-inspection', 'Inspection for newly built homes.'),
    ('home-inspector', 'Condo inspection', 'condo-inspection', 'Inspection services focused on condo units.'),
    ('home-inspector', 'Thermal imaging', 'thermal-imaging', 'Thermal camera inspection for moisture and insulation concerns.'),
    ('real-estate-lawyer', 'Purchase closings', 'purchase-closings', 'Legal support for buyer-side purchase closings.'),
    ('real-estate-lawyer', 'Sale closings', 'sale-closings', 'Legal support for seller-side closings.'),
    ('real-estate-lawyer', 'Mortgage refinancing', 'mortgage-refinancing', 'Legal support for mortgage refinance transactions.'),
    ('real-estate-lawyer', 'Title review', 'title-review', 'Title, lien, and registration review.'),
    ('notary', 'Document notarization', 'document-notarization', 'Notarizing real estate and identity documents.'),
    ('notary', 'Remote online notarization', 'remote-online-notarization', 'Remote notary service where permitted.'),
    ('appraiser', 'Residential appraisals', 'residential-appraisals', 'Valuations for houses, condos, and small residential properties.'),
    ('appraiser', 'Estate appraisals', 'estate-appraisals', 'Valuations for estate and probate needs.'),
    ('appraiser', 'Market rent analysis', 'market-rent-analysis', 'Rental value and market rent assessment.'),
    ('insurance-broker', 'Home insurance', 'home-insurance', 'Insurance guidance for homeowners and buyers.'),
    ('insurance-broker', 'Condo insurance', 'condo-insurance', 'Insurance support for condo owners.'),
    ('insurance-broker', 'Landlord insurance', 'landlord-insurance', 'Coverage for rental and investment properties.'),
    ('insurance-broker', 'Title insurance', 'title-insurance', 'Title insurance support for real estate transactions.'),
    ('contractor', 'Renovations', 'renovations', 'Renovation planning, repair, and improvement services.'),
    ('contractor', 'Basement finishing', 'basement-finishing', 'Basement finishing and remodeling services.'),
    ('contractor', 'Kitchen remodels', 'kitchen-remodels', 'Kitchen renovation and upgrade services.'),
    ('contractor', 'Bathroom remodels', 'bathroom-remodels', 'Bathroom renovation and upgrade services.'),
    ('contractor', 'Pre-listing repairs', 'pre-listing-repairs', 'Repairs before listing a property.'),
    ('electrician', 'Panel upgrades', 'panel-upgrades', 'Electrical panel replacement and capacity upgrades.'),
    ('electrician', 'EV charger installation', 'ev-charger-installation', 'Electric vehicle charger installation.'),
    ('electrician', 'Lighting upgrades', 'lighting-upgrades', 'Interior and exterior lighting work.'),
    ('plumber', 'Fixture replacement', 'fixture-replacement', 'Faucet, toilet, sink, and fixture replacement.'),
    ('plumber', 'Leak repair', 'leak-repair', 'Leak investigation and plumbing repair.'),
    ('plumber', 'Water heater service', 'water-heater-service', 'Water heater installation and repair.'),
    ('hvac-technician', 'Furnace service', 'furnace-service', 'Furnace repair, maintenance, and replacement.'),
    ('hvac-technician', 'Air conditioning service', 'air-conditioning-service', 'Air conditioning repair, maintenance, and replacement.'),
    ('hvac-technician', 'Duct cleaning', 'duct-cleaning', 'Duct cleaning and airflow improvement.'),
    ('roofer', 'Roof inspection', 'roof-inspection', 'Roof condition assessments and reports.'),
    ('roofer', 'Shingle replacement', 'shingle-replacement', 'Shingle roof repair and replacement.'),
    ('roofer', 'Gutter repair', 'gutter-repair', 'Gutter repair, replacement, and drainage support.'),
    ('landscaper', 'Curb appeal refresh', 'curb-appeal-refresh', 'Outdoor updates before listing a property.'),
    ('landscaper', 'Lawn care', 'lawn-care', 'Seasonal lawn care and maintenance.'),
    ('landscaper', 'Snow removal', 'snow-removal', 'Winter snow and ice management.'),
    ('pest-control-specialist', 'Termite inspection', 'termite-inspection', 'Inspection and treatment for termite concerns.'),
    ('pest-control-specialist', 'Rodent control', 'rodent-control', 'Rodent prevention and removal services.'),
    ('pest-control-specialist', 'Pre-sale pest treatment', 'pre-sale-pest-treatment', 'Pest treatment before listing or closing.'),
    ('real-estate-photographer', 'Listing photography', 'listing-photography', 'Interior and exterior property photography.'),
    ('real-estate-photographer', 'Video walkthroughs', 'video-walkthroughs', 'Property walkthrough video production.'),
    ('real-estate-photographer', 'Drone media', 'drone-media', 'Aerial photos and video for listings.'),
    ('real-estate-photographer', 'Floor plans', 'floor-plans', 'Measured floor plan creation.'),
    ('home-stager', 'Occupied staging', 'occupied-staging', 'Staging using a seller occupied home.'),
    ('home-stager', 'Vacant staging', 'vacant-staging', 'Furniture and decor staging for empty properties.'),
    ('home-stager', 'Staging consultation', 'staging-consultation', 'Room-by-room preparation advice.'),
    ('interior-designer', 'Space planning', 'space-planning', 'Room layout and space planning services.'),
    ('interior-designer', 'Finish selection', 'finish-selection', 'Paint, flooring, tile, and fixture selection.'),
    ('interior-designer', 'Furniture sourcing', 'furniture-sourcing', 'Furniture and decor sourcing support.'),
    ('architect', 'Permit drawings', 'permit-drawings', 'Drawings for permit and renovation submissions.'),
    ('architect', 'Addition planning', 'addition-planning', 'Design support for additions and structural changes.'),
    ('architect', 'Feasibility review', 'feasibility-review', 'Early review of design and renovation feasibility.'),
    ('surveyor', 'Boundary surveys', 'boundary-surveys', 'Boundary identification and survey plans.'),
    ('surveyor', 'Topographic surveys', 'topographic-surveys', 'Topographic measurement and site plans.'),
    ('surveyor', 'Fence and setback review', 'fence-and-setback-review', 'Fence line and setback support.'),
    ('property-manager', 'Tenant placement', 'tenant-placement', 'Rental marketing and tenant placement.'),
    ('property-manager', 'Rent collection', 'rent-collection', 'Monthly rent collection and owner reporting.'),
    ('property-manager', 'Maintenance coordination', 'maintenance-coordination', 'Maintenance dispatch and vendor coordination.'),
    ('condo-document-reviewer', 'Status certificate review', 'status-certificate-review', 'Review of condo status certificate packages.'),
    ('condo-document-reviewer', 'Reserve fund review', 'reserve-fund-review', 'Review of condo reserve fund information.'),
    ('property-tax-consultant', 'Assessment review', 'assessment-review', 'Property assessment review and comparison.'),
    ('property-tax-consultant', 'Tax appeal support', 'tax-appeal-support', 'Support for property tax appeal preparation.'),
    ('mover', 'Local moves', 'local-moves', 'Local residential moving services.'),
    ('mover', 'Long-distance moves', 'long-distance-moves', 'Regional or long-distance relocation services.'),
    ('mover', 'Packing services', 'packing-services', 'Packing and unpacking support.'),
    ('cleaner', 'Move-in cleaning', 'move-in-cleaning', 'Cleaning before occupancy.'),
    ('cleaner', 'Move-out cleaning', 'move-out-cleaning', 'Cleaning after moving out.'),
    ('cleaner', 'Deep cleaning', 'deep-cleaning', 'Detailed whole-home cleaning.'),
    ('junk-removal-provider', 'Estate cleanouts', 'estate-cleanouts', 'Large cleanouts for estates and inherited properties.'),
    ('junk-removal-provider', 'Construction debris removal', 'construction-debris-removal', 'Removal of renovation and construction debris.'),
    ('junk-removal-provider', 'Donation pickup', 'donation-pickup', 'Pickup and routing of reusable goods.'),
    ('security-system-installer', 'Smart locks', 'smart-locks', 'Smart lock setup and access control.'),
    ('security-system-installer', 'Camera systems', 'camera-systems', 'Security camera planning and installation.'),
    ('security-system-installer', 'Alarm systems', 'alarm-systems', 'Home alarm setup and monitoring preparation.')
) as seed_specialties(category_slug, name, slug, description)
join public.categories
  on categories.slug = seed_specialties.category_slug
on conflict (slug) do update
set
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description;
